import React, { useEffect, useState } from 'react';
import Head from 'next/head';
import { Inter } from 'next/font/google';
import Layout from '@/components/Layout';
import AnimatedText from '@/components/AnimatedText';
import AnimatedLogo from '@/components/AnimatedLogo';
import { motion } from 'framer-motion';

const inter = Inter({ subsets: ['latin'] });

export default function Home() {
  const [titleAnimationComplete, setTitleAnimationComplete] = useState(false);

  const handleTitleAnimationComplete = () => {
    setTitleAnimationComplete(true);
  };

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <main className="flex items-center text-dark w-full min-h-screen">
        <Layout className="pt-0">
          <div className="flex items-center justify-between w-full">
            <AnimatedLogo isAnimationComplete={titleAnimationComplete} />
            <div className="w-1/2 flex flex-col items-center self-center" style={{ marginTop: '-30rem' }}>
              <AnimatedText
                text="Welcome!"
                className="!text-6xl !text-left"
                onAnimationComplete={handleTitleAnimationComplete}
              />
              <AnimatedText text="I&apos;m Sergey, a web and software developer." className="!text-4xl !text-left" />
              <div style={{ height: '4rem' }}>
                {/* Reserve space for the motion.p element */}
                {titleAnimationComplete && (
                  <motion.p initial={{ opacity: 0 }} animate={{ opacity: 1 }} transition={{ duration: 1 }} className="text-2xl mr-20">
                    My main skillset:
                  </motion.p>
                )}
              </div>
            </div>
          </div>
        </Layout>
      </main>
    </>
  );
}